Quando lancio un'eccezione posso usare una di quelle gi√† predefinite in Ruby (146) oppure ne posso creare
io una nuova ma deve derivare da StandardError o uno dei suoi figli, altrimenti non viene agganciata per default.